name: X
main: X\X
version: "1.0"
api: [1.12.0]
author: DeBe
website: https://github.com/DeBe0/PocketMine-Plugins

commands:
 x:
  permission: x.cmd
  usage: /X (All)

permissions:
 x.cmd:
  default: true
  description: X - Command
