name: ServerTP
main: ServerTP\ServerTP
version: "1.0"
api: [1.12.0]
author: MineBlock
description: MineBlock's Plugin
website: http://MineBlock.zz.am

commands:
 servertp:
  permission: servertp.cmd
  description: ServerTP
  usage: /ServerTP <PlayerName> <IP> <Port>

permissions:
 servertp.cmd:
  default: op
  description: ServerTP - Command