name: MineBlock2
main: MineBlock2\MineBlock2
version: "1.1"
api: [1.12.0]
author: DeBe
website: https://github.com/DeBe0/PocketMine-Plugins

commands:
 mineblock2:
  permission: mineblock2.cmd
  description: <On|Regen|Block|Delay|Count|Drop|IsDrop|IsSafe>
  usage: /Mineblock <On|Regen|Block|Delay|Count|Drop|IsDrop|IsSafe>

permissions:
 mineblock2.cmd:
  default: op
  description: MineBlock2 - Command