name: ChatSwitch
main: ChatSwitch\ChatSwitch
version: "1.0"
api: [1.12.0]
author: DeBe
website: http://DeBe.ml

commands:
 chatswitch:
  permission: chatswitch.cmd
  description: Switching
  usage: /ChatSwitch

permissions:
 chatswitch.cmd:
  default: true
  description: ChatSwitch - Command