name: Shop
main: Shop\Shop
version: "1.1"
api: [1.12.0]
author: DeBe
website: https://github.com/DeBe0/PocketMine-Plugins

commands:
 shop:
  permission: shop.cmd
  description: <Add|Del|Change|Reset|Edit>
  usage: /Shop <Add|Del|Change|Reset|Edit>

permissions:
 shop.cmd:
  default: op
  description: Shop - Command