name: MineFarm
main: MineFarm\MineFarm
version: "2.0"
api: [1.12.0]
author: DeBe
website: https://github.com/DeBe0/PocketMine-Plugins

commands:
 myfarm:
  permission: minefarm.myfarm.cmd
  description: <Move|Buy|Color|Visit|Invite|Share|Kick|AllKick|List|Here>
  usage: /MyFarm <Move|Buy|Color|Visit|Invite|Share|Kick|AllKick||List|Here>
 minefarm:
  permission: minefarm.minefarm.cmd
  description: <Give|Move|Here|Auto|Sell|Price|ColorSell|ColorPrice|Item|List|Color>
  usage: /MineFarm <Give|Move|Here|Auto|Sell|Price|ColorSell|ColorPrice|Item|List|Color>

permissions:
 minefarm.myfarm.cmd:
  default: true
  description: MineFarm - MyFarm - Command
 minefarm.minefarm.cmd:
  default: op
  description: MineFarm - MineFarm - Command
 minefarm.move:
  default: op
  description: MineFarm - Move
 minefarm.block:
  default: op
  description: MineFarm - Block