name: MineFarm
main: MineFarm\MineFarm
version: "1.2"
api: [1.12.0]
author: Kawa

commands:
 myfarm:
  permission: minefarm.myfarm.cmd
  description: <Move|Buy|Color|Visit|Invite|Share|Kick|List|Here>
  usage: /MyFarm <Move|Buy|Color|Visit|Invite|Share|Kick|List|Here>
 minefarm:
  permission: minefarm.minefarm.cmd
  description: <Give|Move|Here|Distance|Size|Air|Auto|Sell|Price|ColorSell|ColorPrice|Item|List|Reset|Color>
  usage: /MineFarm <Give|Move|Here|Distance|Size|Air|Auto|Sell|Price|ColorSell|ColorPrice|Item|List|Reset|Color>

permissions:
 minefarm.myfarm.cmd:
  default: true
  description: MineFarm - MyFarm - Command
 minefarm.minefarm.cmd:
  default: op
  description: MineFarm - MineFarm - Command
 minefarm.move:
  default: op
  description: MineFarm - Move
 minefarm.block:
  default: op
  description: MineFarm - Block