name: Login
main: Login\Login
version: "1.1"
api: [1.12.0]
author: DeBe
website: https://github.com/DeBe0/PocketMine-Plugins

commands:
 login:
  permission: login.cmd
  description: <Password>
  usage: /Login <Password>
 register:
  permission: register.cmd
  description: <Password> <Password>
  usage: /Register <Password> <Password>
 change:
  permission: change.cmd
  decription: <NewPassword>
  usage: /Change <NewPassWord>
 loginop:
  permission: loginop.cmd
  description: <UnRegister|Change|Protect|Auto>
  usage: /LoginOP <UnRegister|Change|Protect|Auto> 

permissions:
 login.cmd:
  default: true
  description: Login - Login - Command
 register.cmd:
  default: true
  description: Login - Register - Command
 change.cmd:
  default: true
  description: Login - Change - Command
 loginop.cmd:
  default: op
  description: Login - LoginOP - Command