name: MineFarm
main: MineBlock\MineFarm\MineFarm
version: "1.0"
api: [1.12.0]
author: MineBlock
description: MineBlock's Plugin
website: http://MineBlock.zz.am


commands:
 myfarm:
  permission: minefarm.myfarm.cmd
  description: MineFarm
  usage: /MyFarm <Move|Buy|Visit|Invite|Share|Kick|List|Here>
 minefarm:
  permission: minefarm.minefarm.cmd
  description: MineFarm
  usage: /MineFarm <Give|Move|Here|Distance|Size|Air|Auto|Sell|Price|Item|List|Reset>

permissions:
 minefarm.myfarm.cmd:
  default: true
  description: MineFarm - MyFarm - Command
 minefarm.minefarm.cmd:
  default: op
  description: MineFarm - MineFarm - Command
 minefarm.move:
  default: op
  description: MineFarm - Move
 minefarm.block:
  default: op
  description: MineFarm - Block