name: X
main: X\X
version: "1.0"
api: [1.12.0]
author: DeBe

commands:
 x:
  permission: x.cmd
  usage: /X <Name> <NewName>

permissions:
 x.cmd:
  default: op
  description: X - Command